import type { Metadata } from "next";

import "./globals.css";

import { JSX, ReactNode } from "react";
import Provider from "./Provider";
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "Token_Sender",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: ReactNode }): JSX.Element {

  return (
    <html lang="en">
      <body>
        <Provider>
          <Header/>
        {props.children}
        </Provider>
      </body>
    </html>
  );
}
